---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  vars:
    client_link: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.10/openshift-client-linux-4.10.51.tar.gz 
    #client_link: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.12/openshift-client-linux-4.12.2.tar.gz 
    install_link: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.12/openshift-install-linux-4.12.2.tar.gz
  connection: local
  become: yes
  tasks:

  - debug:
      msg:
      - "Install Link: {{ client_link }}"
      - "Client Link: {{ install_link }}"

  - name: Install a list of Dev tools
    dnf:
      name:
        - vim
        - tree
        - unzip
        - wget
        - curl
        - git
        - httpd-tools
      state: present

  - name: Setup oc completion
    shell: "oc completion bash >/etc/bash_completion.d/openshift"

  - name: Download and unpack AWS CLI
    unarchive:
      src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: ./
      remote_src: yes
    tags: aws

  - name: Install AWS CLI
    shell: "./aws/install -i /usr/local/aws-cli -b /usr/local/bin"
    tags: aws

  - name: Cleanup AWS CLI files
    file:
      path: awscli-bundle
      state: absent
    tags: aws

  - name: Download and unpack Openshift 4 client
    unarchive:
      src: "{{ client_link }}"
      dest: /usr/bin
      remote_src: yes

  - name: Download and unpack Openshift 4 installer
    unarchive:
      src: "{{ install_link }}"
      dest: /usr/bin
      remote_src: yes

  - name: Setup oc completion
    shell: "oc completion bash >/etc/bash_completion.d/openshift"
